ruby spec/command_post/command/command_spec.rb
ruby spec/command_post/config/app_config_spec.rb
ruby spec/command_post/identity/identity_lookup_value_aggregate_id_spec.rb
ruby spec/command_post/identity/identity_lookup_value_checksum_spec.rb
ruby spec/command_post/identity/identity_lookup_value_field_spec.rb
ruby spec/command_post/persistence/data_validation_spec.rb
ruby spec/command_post/persistence/indexing_spec.rb
ruby spec/command_post/persistence/schema_validation_spec.rb